b=set()
b.add(5)
b.add(1)
b.add(10)
b.add(("Santosh","Bhandari"))
# print(b)
# print(len(b))
# b.remove(1)
# print(b)
print(b)
print(b.pop())
print(b)
# b.clear()
# print(b)
a={1,2,3,4,5,6,7,8,9,10}
print(b.union(a))
print(b.intersection(a))